name: Deploy to GitHub Pages

on:
    push:
        branches: 
            - master
            
permissions:
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-slim
        defaults:
            run:
                working-directory: ./gravensoft-website
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'npm'
                cache-dependency-path: './gravensoft-website/package-lock.json'
            
            - name: Install Node Dependencies
              run: npm ci

            - name: Build Website
              run: npm run build

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: gravensoft-website/dist
                branch: live